README.md, js/Jenkinsfile, js/package-lock.json, js/package.json
=> chore: add Jenkinsfile for Javascript implementation

js/Jenkinsfile
For `@*/*` scoped packages we need to add `--access=public` on `npm publish`, as by default they are private.
=> Add '--access=public' to npm publish command

java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/spi/framework/nodejs/NodeJsFrameworkDetectorProvider.java
It's not an error finding a package.json without the dependencies section. It won't happen often but when it happens we shouldn't print an error in logs.
=> fix: prevent from logging error if dependencies section is missing in package.json

.github/workflows/release.yml
I remember we already faced this issue. By updating the changelog action it should be fixed. Or, last time, we recreated the changelog manually?
=> chore(skip-release): update changelog gh action in release workflow (#59)

go/pkg/apis/recognizer/devfile_recognizer.go, go/test/apis/devfile_recognizer_test.go, go/test/apis/language_recognizer_test.go
This adds the basic devfile detection we have in java. It takes a list of devfile and return the one that matches the most.
@kadel for your use case do you prefer to send a registry url to alizer and receive the selected devfile or you will use this method (sending a list of devfiles and have the one that matches the most returned)?
=> feat: devfile detection implemented in go

go/pkg/apis/enricher/dotnet_enricher.go, go/pkg/apis/enricher/enricher.go, go/pkg/apis/enricher/framework/dotnet/dotnet_detector.go, go/pkg/schema/dotnet_proj.go, go/pkg/utils/detector.go, go/pkg/utils/langfiles/resources/languages-customization.yml, go/test/apis/language_recognizer_test.go
it resolves #72 
This does not contain tests for devfiles as the devfile algorithm needs to use component detection to avoid wrong results and component detection is still on-going #64
=> feat: add .net detection in go impl (#72)

go/pkg/apis/enricher/go_enricher.go, go/pkg/apis/recognizer/component_recognizer.go, go/pkg/apis/recognizer/devfile_recognizer.go, go/pkg/apis/recognizer/language_recognizer.go, go/pkg/schema/languages.go, go/pkg/utils/langfiles/languages_file_handler.go, go/test/apis/component_recognizer_test.go, go/test/apis/devfile_recognizer_test.go
@kadel This PR should improve the detection as we discussed last time. You won't need to use analyze anymore (atleast i don't think it would be very useful for odo) but do component detection or select devfile directly.
So now what we have is:
**analyze** -> just perform an analysis of all files from the root. It just gives an overview of what's inside the root
**component detection** -> it detects components within the root. If there is a component living in the root it will be in first position of the returned list. If you want infos about the languages used by a component you should use the languages field of the component itself. First language in the list is the main one.
**devfile detection** -> tries to detect a component in the root and return a devfile for it. If there is no …
=> feat: pick devfile based on component detection and remove framework constraint

go/pkg/schema/languages.go, go/pkg/utils/langfiles/languages_file_handler.go, go/pkg/utils/langfiles/resources/languages-customization.yml, resources/languages-customization.yml
it resolves #87 
This is something i was already thinking before and it was raised again by https://github.com/redhat-developer/alizer/issues/84 
Why `GCC Machine Description` files (`.md`) should be treated as a programming language? I didn't find any valid reason so far and even if we change our mind in future we can just revert the disable flag from our customization file.
=> chore: remove GCC Machine Description from programming langs used for detection (#87)

go/pkg/apis/recognizer/language_recognizer.go
This fixes #99 
The problem was that if a single file matched a rule in gitignore, the whole folder was skipped. So if the file was in the root, no component were detected as only the files discovered until that moment would be used.
E.g I have this treeview
```
root 
| -  .classpath (file)
| -  .settings  (file)
| -  src/  (folder)
| -  test/ (folder)
```
The gitignore is like
```
.classpath
....
```
When Alizer walks on the `.classpath` file, it matches the rule in gitignore and all folder is skipped. 
Code in path lib which caused the misbehaviour
```
for _, name := range names {
filename := Join(path, name)
fileInfo, err := lstat(filename)
err = walk(filename, fileInfo, walkFn) -> here i returned a skipDir even if it was a file
if err != nil {
if !fileInfo.IsDir() || err != SkipDir { …
```
=> fix: prevent skipping current folder if only a single file needs to be ignored (#99)

java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/ComponentRecognizer.java, java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/ComponentRecognizerImpl.java, java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/DevFileRecognizerImpl.java, java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/Recognizer.java, java/alizer-api/src/test/java/com/redhat/devtools/alizer/api/ComponentRecognizerTest.java
it resolves #88 
This patch update how the detection works in JAVA to make it be the same as in Go.
The component detection works without framework constraint and the result is ordered to have the component found in root in first position.
The devfile detection is now based on component detection. A devfile is picked based on component in root, if nothing is there it uses a component in the project or the generic analyze action.
I added some comment to keep track of the behavior.
=> feat: update component/devfile detection in JAVA (#88)

go/pkg/utils/langfiles/resources/languages-customization.yml, resources/languages-customization.yml
Adds ".NET" alias to all places that already list "donet" as an alias
https://github.com/devfile/registry/pull/134 [updated Devfiles](https://github.com/devfile/registry/pull/134/files#diff-01e78547ca4478cb2cd863da31ce6bf19a71387b5a27f16ce270d7c48f725581R7), and they now have `language: .NET` because of this, Alizer is no longer able to match .NET project to correct Devfiles. 
This should fix it.
=> Add .NET alias

go/pkg/apis/enricher/javascript_enricher.go
Just discovered there are some devfiles that use tag `Node.JS` (eg https://registry.devfile.io/viewer/devfiles/Community+nodejs-angular)  and others `NodeJS` (e.g https://registry.devfile.io/viewer/devfiles/Community+nodejs-basic).
=> feat: add Node.JS as tool for JS/TS because of new devfile tag

go/docs/port_detection.md, go/pkg/apis/enricher/enricher.go, go/test/apis/component_recognizer_test.go, resources/projectPortTesting/projectContainerFile/Containerfile, resources/projectPortTesting/projectContainerFile/package.json, resources/projectPortTesting/projectContainerFile/server.js
Containerfile is an alternate name for Dockerfile. They support the same syntax. See:
https://github.com/containers/common/blob/main/docs/Containerfile.5.md
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>
=> feat: add support for Containerfile

.github/workflows/CI.yml, go/pkg/apis/enricher/framework/javascript/nodejs/next_detector.go, go/pkg/apis/enricher/java_enricher.go, go/pkg/schema/package_json.go, go/pkg/utils/detector.go, go/test/apis/git_recognizer_test.go, go/test/git_test.json
Repos added:
[https://github.com/JoranBergfeld/webshop.git](https://github.com/JoranBergfeld/webshop.git)
[https://github.com/bezkoder/spring-boot-data-jpa-mysql.git](https://github.com/bezkoder/spring-boot-data-jpa-mysql.git)
[https://github.com/kylebuch8/urgent-care-finder-v2.git](https://github.com/kylebuch8/urgent-care-finder-v2.git)
[https://github.com/rh-aiservices-bu/object-detection-rest.git](https://github.com/rh-aiservices-bu/object-detection-rest.git)
[https://github.com/gothinkster/spring-boot-realworld-example-app](https://github.com/gothinkster/spring-boot-realworld-example-app)
[https://github.com/spring-guides/gs-batch-processing](https://github.com/spring-guides/gs-batch-processing) -> it contains both maven and gradle config file. Gradle is the one that always win and …
=> chore: extend test suite

go/pkg/apis/enricher/javascript_enricher.go, go/pkg/apis/model/model.go, go/pkg/apis/recognizer/component_recognizer.go, go/pkg/apis/recognizer/devfile_recognizer.go, go/pkg/cli/devfile/devfile.go, go/pkg/utils/detector.go, go/pkg/utils/langfiles/resources/languages-customization.yml, go/test/apis/component_recognizer_test.go, go/test/apis/devfile_recognizer_test.go, go/test/apis/git_recognizer_test.go, go/test/git_test.json, java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/ComponentRecognizerImpl.java, resources/languages-customization.yml
it resolves #114 https://github.com/redhat-developer/alizer/issues/117
This patch contains some improvements to solve the issue faced with the `quarkus super heroes ui` app.
- it checks devDependencies to search for the framework
- it accepts multiple components detection in same path (e.g java and typescript in the root)
- it adds a new method to retrieve a list of devfiles for the project
- JavaScript and TypeScript are considered equivalent when picking a devfile. So a ts devfile is valid for a js project and viceversa.
The ouput of the `quarkus super heroes ui` app is 
```
[
{
"Name": "java-maven",
"Language": "Java",
"ProjectType": "Maven",
"Tags": [
"Java",
"Maven"
]
},
{
"Name": "java-openliberty",
"Language": "Java",
"ProjectType": "Open Liberty",
"Tags": [
"Java",
"Maven"
]
},
{ …
```
=> feat: return multiple devfiles when having multiple components

.github/workflows/release.yml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
=> Use commit SHA instead of branch name for third-party actions

README.md, docs/public/alizer-spec.md, go/README.md, go/docs/port_detection.md, java/README.md, js/README.md
This PR separates the usage guides and includes them inside each different implementation (Go, Java, JS).
fixes https://github.com/redhat-developer/alizer/issues/149
=> Create separate usage guides per implemenation and clean root readme

go/pkg/apis/enricher/framework/python/django_detector.go, go/pkg/apis/enricher/framework/python/flask_detector.go, go/pkg/apis/enricher/python_enricher.go, go/pkg/utils/langfiles/resources/languages-customization.yml, go/test/git_test.json, resources/languages-customization.yml
It adds a list of `configuration_files` inside the `languages-customization.yaml` file:
```yaml
Python:
configuration_files:
- "pyproject.toml"
- "requirements.txt"
component: true
```
This allows the `component_recognizer` to be able to recognize `Python` components, from their `configuration_files`, in given projects.
It adds functionality to `DjangoDetector` in order to be able to recognize if a `Python` project has `django` as framework, through `requirements.txt` or `pyproject.toml` files.
It also creates the `FlaskDetector` which allows the `PythonEnricher` to recognize `flask` as framework of a `python` project.
fixes https://github.com/redhat-developer/alizer/issues/165
=> Add Python configuration files to customization and Implement FlaskDetector

go/test/apis/devfile_recognizer_test.go
Inside this [PR](https://github.com/devfile/registry/pull/177) we are introducing the universal image. The current PR is ensuring that we are always checking in our tests that there is no impact of this change (e.g. the universal image devfile is selected first instead of a more related one).
To do this PR adds a new mocked `model.devfileType` instance inside `tests.getDevFileTypes()`:
```golang
{
Name:        "udi",
Language:    "Polyglot",
ProjectType: "default",
Tags: []string{
"Java",
"Maven",
"Scala",
"PHP",
".NET",
"Node.js",
"Go",
"Python",
"Pip",
"ubi8",
},
},
```
fixes https://github.com/redhat-developer/alizer/issues/174
=> Add udi image case for mocked values of devfile types

go/pkg/apis/enricher/enricher.go, go/test/apis/component_recognizer_test.go, resources/projectPortTesting/projectNestedContainerFile/docker/Containerfile, resources/projectPortTesting/projectNestedContainerFile/package.json, resources/projectPortTesting/projectNestedContainerFile/server.js, resources/projectPortTesting/projectNestedDockerFile/docker/Dockerfile, resources/projectPortTesting/projectNestedDockerFile/package.json, resources/projectPortTesting/projectNestedDockerFile/server.js
Upon `enricher.GetPortsFromDockerFile()` it fetches all `locations` from the given `root` path. The main functionality is added with the `enricher.getLocations()` function:
```golang
func getLocations(root string) []string {
locations := []string{"Dockerfile", "Containerfile"}
dirItems, err := ioutil.ReadDir(root)
if err != nil {
return locations
}
for _, item := range dirItems {
if strings.HasPrefix(item.Name(), ".") {
continue
}
tmpPath := fmt.Sprintf("%s%s", root, item.Name())
fileInfo, err := os.Stat(tmpPath)
if err != nil {
continue
}
if fileInfo.IsDir() {
locations = append(locations, fmt.Sprintf("%s/%s", item.Name(), "Dockerfile"))
locations = append(locations, fmt.Sprintf("%s/%s", item.Name(), "Containerfile"))
}
}
return locations
}
```
More detailed, for each `item` it finds …
=> Add second-level dockerfile, containerfile search for Port recognition

go/pkg/apis/enricher/framework/go/go_detector.go, go/pkg/apis/enricher/go_enricher.go, go/test/apis/component_recognizer_test.go, go/test/apis/devfile_recognizer_test.go, resources/projectPortTesting/projectGo/go.mod, resources/projectPortTesting/projectGo/main.go
Implements an additional check for port recognition upon `go_enricher` checks. More detailed, inside the `GoEnricher.DoEnrichComponent` for `case: model.Source` if all checks inside `framework.***Detector.DoPortDetection` have not returned any ports, it runs the `framework.DoGoPortsDetection` in order to check if there are any ports specified inside the root folder of the project.
```golang
case model.Source:
{
for _, detector := range getGoFrameworkDetectors() {
for _, framework := range component.Languages[0].Frameworks {
if utils.Contains(detector.GetSupportedFrameworks(), framework) {
detector.DoPortsDetection(component, ctx)
}
}
}
if len(component.Ports) == 0 {
framework.DoGoPortsDetection(component, ctx)
}
}
}
```
The `framework.DoGoPortsDetection` uses the same functionality for …
=> Enhance go port recognition

go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go, go/pkg/utils/detector.go, go/test/apis/component_recognizer_test.go, go/test/apis/devfile_recognizer_test.go, resources/projectPortTesting/projectExpressEnvLogicalOROperator/app.js, resources/projectPortTesting/projectExpressEnvLogicalOROperator/html/index.html, resources/projectPortTesting/projectExpressEnvLogicalOROperator/package-lock.json, resources/projectPortTesting/projectExpressEnvLogicalOROperator/package.json
Updates the port recognition logic for `express_detector`. Moreover, it adds an additional check for cases that we use a variable which takes its value after the usage of the logical OR operator (e.g. `var PORT = process.env.PORT || 8080`). The new logic for the `func getPort` of the detector will be:
Note that all other detectors (`angular`, `next`, `nodejs`, `nuxt`, `reactjs`, `svetle`, and `vue`) are not using the same logic in order to perform port recognition, that's why this workaround is not global for nodejs detectors.
This PR is part of the solution and fixes https://github.com/redhat-developer/alizer/issues/146
=> Fix express.js port recognition

go/go.mod, go/pkg/utils/cache_test.go, go/pkg/utils/detector.go, go/pkg/utils/detector_test.go, go/pkg/utils/langfiles/languages_file_handler_test.go, go/pkg/utils/testdata/composer.json, go/pkg/utils/testdata/package.json, go/pkg/utils/testdata/pom-dependency.xml, go/pkg/utils/testdata/pom-plugin.xml, go/pkg/utils/testdata/pom-profile.xml
adds unit tests for [pkg/utils](https://github.com/redhat-developer/alizer/tree/main/go/pkg/utils)
fixes #206 
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.
=> adding utils unit tests

go/pkg/apis/enricher/enricher.go, go/pkg/apis/enricher/framework/dotnet/dotnet_detector.go, go/pkg/apis/enricher/framework/go/echo_detector.go, go/pkg/apis/enricher/framework/go/fasthttp_detector.go, go/pkg/apis/enricher/framework/go/gin_detector.go, go/pkg/apis/enricher/framework/go/go_detector.go, go/pkg/apis/enricher/framework/go/gofiber_detector.go, go/pkg/apis/enricher/framework/go/mux_detector.go, go/pkg/apis/enricher/framework/java/micronaut_detector.go, go/pkg/apis/enricher/framework/java/openliberty_detector.go, go/pkg/apis/enricher/framework/java/quarkus_detector.go, go/pkg/apis/enricher/framework/java/spring_detector.go, go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go, go/pkg/apis/enricher/java_enricher.go, go/pkg/apis/recognizer/devfile_recognizer.go, go/pkg/utils/detector.go, go/pkg/utils/langfiles/languages_file_handler.go, go/test/apis/component_recognizer_test.go
Fixes several warnings from gosec security check:
* Potential file inclusion: It fixes the issue by using the `filepath.Clean()` func before using the `os.Open()` func.
* Defering unsafe method: Adds error handling cases inside defer funcs used for `file.Close()` funcs.
* Errors unhandled: For each `Unmarshal()` func used without error handling, it adds the appropriate error handling.
Fixes #222 
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.
=> Fix gosec warnings

.github/workflows/release.yaml, README.md
Introduces the `release.yaml` workflow which will add 5 binaries into an existing release. Those will be:
```yaml
goosarch:
- 'darwin/amd64'
- 'linux/amd64'
- 'linux/ppc64le'
- 'linux/s390x'
- 'windows/amd64'
```
The flow of a release would require a user to push a tag in order to trigger this workflow. As a result those 5 binaries will be added to the tag.
Our release process remains the same:
- Create a new release with a new tag.
- The tag has to start with "v" in order to trigger the binary creation job.
- [Optional] Autogenerate the release notes
- Creating the release with a new "v" tag triggers the `release.yaml`
- The binaries are added to the new tag and they are reachable through the new release.
fixes #40 
Testing and documentation do not need to be complete in order for this …
=> Add binaries to every new release

README.md
Adds a deprecated warning to the readme
part of https://github.com/redhat-developer/alizer/issues/240
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.
=> adding deprecation warning to readme
