api/pom.xml, app/pom.xml, pom.xml
=> Fix Maven coordinates

api/src/main/java/com.redhat.devtools.recognizer.api/LanguageRecognizerBuilder.java, api/src/main/java/com.redhat.devtools.recognizer.api/LanguageRecognizerImpl.java, api/src/test/java/com/redhat/devtools/recognizer/LanguageRecognizerTest.java, app/src/main/java/com/redhat/devtools/recognizer/app/MainApp.java
=> refactor: introduce builder

.github/workflows/CI.yml
=> chore: Add native build

alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/AnalyzeCommand.java, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/BaseCommand.java, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/DevfileCommand.java, alizer-cli/src/main/resources/application.properties
=> refactor: Add sub commands to CLI

alizer-api/src/main/java/com/redhat/devtools/alizer/api/DevfileType.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/Language.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageFileHandler.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageFileItem.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageRecognizer.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageRecognizerBuilder.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageRecognizerImpl.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageScore.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/spi/JavaLanguageEnricherProviderImpl.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/spi/LanguageEnricherProvider.java, alizer-api/src/main/java/com/redhat/devtools/alizer/api/spi/PythonLanguageEnricherProviderImpl.java, alizer-api/src/main/resources/META-INF/services/com.redhat.devtools.alizer.api.spi.LanguageEnricherProvider, alizer-api/src/main/resources/META-INF/services/com.redhat.devtools.recognizer.api.spi.LanguageEnricherProvider, alizer-api/src/test/java/com/redhat/devtools/alizer/api/AbstractRecognizerTest.java, alizer-api/src/test/java/com/redhat/devtools/alizer/api/LanguageRecognizerTest.java, alizer-api/src/test/java/com/redhat/devtools/alizer/api/LanguageScoreTest.java, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/AnalyzeCommand.java, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/DevfileCommand.java, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/DevfileTypeAdapter.java
=> chore: rename packages to alizer

alizer-cli/pom.xml, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/AnalyzeCommand.java, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/BaseCommand.java, alizer-cli/src/main/java/com/redhat/devtools/alizer/cli/DevfileCommand.java, alizer-cli/src/main/resources/templates/AnalyzeCommand/result.json, alizer-cli/src/main/resources/templates/AnalyzeCommand/result.txt, alizer-cli/src/main/resources/templates/DevfileCommand/result.json, alizer-cli/src/main/resources/templates/DevfileCommand/result.txt
=> Add JSON output to CLI

alizer-cli/src/main/resources/templates/DevfileCommand/result.json
=> fix: JSON out was invalid for devfile command

CONTRIBUTING.md, README.md
=> docs: Add README

alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageRecognizerImpl.java
=> fix: Use caller's class loader when loading LanguageEnricher

js/resources/languages.yaml, js/src/constants.ts, js/src/recognizer.ts, js/src/types.ts, js/test/recognizer.test.ts
=> feat: add devfile selection in js impl (#33)

java/alizer-api/pom.xml, java/alizer-cli/pom.xml, java/alizer-registry-support/pom.xml, java/pom.xml
=> chore(skip-release): Prepare 0.1.0

java/alizer-api/pom.xml, java/alizer-cli/pom.xml, java/alizer-registry-support/pom.xml, java/pom.xml
=> chore(skip-release): Bump to 0.2.0

README.md
Updated this PR as https://github.com/redhat-developer/alizer/pull/54 was similar. This also has an update for readme file
=> docs: Add component detection section to Readme

docs/public/alizer-spec.md, go/README.md
=> docs: update readme in go impl (#61)

.github/workflows/checkLang.yml, .gitignore, go/go.mod, go/pkg/apis/enricher/enricher.go, go/pkg/apis/enricher/framework/java/java_detector.go, go/pkg/apis/enricher/framework/java/micronaut_detector.go, go/pkg/apis/enricher/framework/java/openliberty_detector.go, go/pkg/apis/enricher/framework/java/quarkus_detector.go, go/pkg/apis/enricher/framework/java/spring_detector.go, go/pkg/apis/enricher/framework/java/vertx_detector.go, go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go, go/pkg/apis/enricher/framework/javascript/nodejs/nodejs_detector.go, go/pkg/apis/enricher/framework/python/django_detector.go, go/pkg/apis/enricher/framework/python/python_detector.go, go/pkg/apis/enricher/java_enricher.go, go/pkg/apis/enricher/javascript_enricher.go, go/pkg/apis/enricher/python_enricher.go, go/pkg/apis/recognizer/devfile_recognizer.go, go/pkg/apis/recognizer/language_recognizer.go, go/pkg/utils/detector.go, go/pkg/utils/langfiles/languages_file_handler.go, go/pkg/utils/langfiles/resources/languages-customization.yml, go/pkg/utils/langfiles/resources/languages.yml, go/test/apis/devfile_recognizer_test.go, go/test/apis/language_recognizer_test.go
=> chore: update module name, add langs files in go module + gh action to check their state

go/pkg/apis/enricher/dotnet_enricher.go, go/pkg/apis/enricher/enricher.go, go/pkg/apis/enricher/framework/java/java_detector.go, go/pkg/apis/enricher/framework/java/micronaut_detector.go, go/pkg/apis/enricher/framework/java/openliberty_detector.go, go/pkg/apis/enricher/framework/java/quarkus_detector.go, go/pkg/apis/enricher/framework/java/spring_detector.go, go/pkg/apis/enricher/framework/java/vertx_detector.go, go/pkg/apis/enricher/framework/javascript/nodejs/reactjs_detector.go, go/pkg/apis/enricher/framework/python/django_detector.go, go/pkg/apis/enricher/framework/python/python_detector.go, go/pkg/apis/enricher/java_enricher.go, go/pkg/apis/enricher/javascript_enricher.go, go/pkg/apis/enricher/python_enricher.go, go/pkg/apis/recognizer/component_recognizer.go, go/pkg/apis/recognizer/language_recognizer.go, go/pkg/schema/languages.go, go/pkg/schema/pom_xml.go, go/pkg/utils/detector.go, go/pkg/utils/langfiles/languages_file_handler.go, go/test/apis/component_recognizer_test.go
=> feat: add component detection in go (#49)

README.md, docs/public/alizer-spec.md, go/README.md
it resolves #85 
The documentation has been updated to reflect the latest changes made.
=> docs: update documentation to describe current state of Alizer (#85)

go/go.mod, go/go.sum, go/pkg/apis/recognizer/component_recognizer.go, go/pkg/apis/recognizer/language_recognizer.go, go/test/apis/component_recognizer_test.go
=> feat: use gitignore file when scanning project (#21)

java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageFileHandler.java, java/alizer-api/src/main/java/com/redhat/devtools/alizer/api/LanguageFileItem.java
=> fix: remove GCC Machine Description from programming langs used for detection in JAVA (#93)

README.md, go/README.md, go/pkg/apis/model/model.go, go/pkg/apis/recognizer/language_recognizer.go, go/test/apis/devfile_recognizer_test.go
=> refactor: rename UsageInPercentage to Weight (#77)

go/Makefile
=> fix: add working build command for windows in makefile (#104)

go/docs/testing_detection.md, go/pkg/apis/enricher/framework/javascript/nodejs/express_detector.go, go/pkg/schema/package_json.go, go/pkg/schema/pom_xml.go, go/pkg/utils/detector.go, go/test/apis/git_recognizer_test.go, go/test/git_test.json, go/test/git_utils.go
=> feat: add git repos for testing and enhance detection (#110)

.snyk
=> Add Snyk exclusion file

README.md
It defines a very simple release process inside the main `Readme.md` file of the project.
fixes https://github.com/redhat-developer/alizer/issues/151
=> Define a Release process

go/docs/port_detection.md, go/test/apis/devfile_recognizer_test.go
Updates the `go/docs/port_detection.md` file after the recent addition to port detection functionality
fixes #185
=> Update port detection docs

docs/proposals/support_22x_devfiles.md
Imports the proposal for EPIC #159
Fixes #225 
Testing and documentation do not need to be complete in order for this PR to be approved. We just need to ensure tracking issues are opened.
=> Add support for 2.2.x devfile proposal
